name: Nightly Build and Push to DockerHub

on:
  schedule:
    - cron: "45 8 * * *"  # Runs every day at 12 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  

      - name: Run Tests
        run: |
          pytest 

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: test  # Only runs if tests pass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Web Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-web:nightly -f Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-web:nightly

      - name: Build and Push Celery Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-celery:nightly -f Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-celery:nightly

  email-failure:
    name: Email on Failure
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send Notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: chance.hintz38@ethereal.email
          password: z7UrtPGsrn7zFKMRKD
          subject: "🚨 Nightly Build Failed!"
          to: "lsng@dons.usfca.edu"
          from: "GitHub Actions <noreply@github.com>"
          body: "The nightly build for the repository has failed. Check GitHub Actions for details."

  email-success:
    name: Email on Failure
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Send Notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: chance.hintz38@ethereal.email
          password: z7UrtPGsrn7zFKMRKD
          subject: "Nightly Build SUCCESS!"
          to: "lsng@dons.usfca.edu"
          from: "GitHub Actions <noreply@github.com>"
          body: "The nightly build for the repository IS SUCCESSFUL!!!"
